version: '3'

services:
    flask:
        build:
            context: .
            dockerfile: ./flask/Dockerfile
        container_name: flask_backend_dip
        networks:
            dipnet_test:
                ipv4_address: 172.10.18.02

    nginx:
        build: ./nginx
        container_name: nginx_backend_dip
        ports:
            - "80:80"
        networks:
            dipnet_test:
                ipv4_address: 172.10.18.03
#    tensormodel:
#        image: tensorflow/serving:2.1.0-rc1
#        volumes:
#            - ./TensorflowServing:/models/FDSmodel
#        environment:
#            - MODEL_NAME=FDSmodel
#        networks:
#            appnet2:
#            ipv4_address: 172.18.18.04
networks:
    dipnet_test:
        ipam:
            driver: default
            config:
                - subnet: 172.10.18.0/24

